In [1]:
import cv2

In [20]:
import cv2
import numpy as np

image = cv2.imread('clouds.jpg')

#creates a matrix of ones, X75
M = np.ones(image.shape, dtype ="uint8")*100

#we use this matrix M, and it to increase the brightness
added = cv2.add(image,M)
cv2.imshow('added',added)

subtra = cv2.subtract(image,M)
cv2.imshow('subtracted',subtra)

cv2.imshow('orignal',image)

cv2.waitKey()
cv2.destroyAllWindows()

[[[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 ..., 
 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ..., 
  [75 75 75]
  [75 75 75]
  [75 75 75]]]


In [8]:
print(M)

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]
